services:
  tubearchivist:
    restart: unless-stopped
    image: bbilly1/tubearchivist
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/media:/youtube
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/cache:/cache
    environment:
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=https://$HOST  # set your host name with protocol and port
      - TA_USERNAME=$TA_USERNAME           # your initial TA credentials
      - TA_PASSWORD=$TA_PASSWORD              # your initial TA credentials
      - TZ=$TZ                 # set your time zone
      - REDIS_CON=redis://archivist-redis:6379
      - ES_URL=http://archivist-es:9200
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - traefik.enable=true
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.entryPoints=websecure
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)'
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt
      - traefik.http.routers.$COMPOSE_PROJECT_NAME.tls=true
      - traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8000
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$HOST/"
      - "homepage.description=$HOME_DESCRIPTION"
    depends_on:
      - archivist-redis
      - archivist-es

  archivist-redis:
    image: redis
    restart: unless-stopped
    # expose:
    #   - "6379"
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/redis:/data
  
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.18.2
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    # expose:
    #   - "9200"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    