services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - SYMFONY__ENV__SECRET=$SECRET
      - SYMFONY__ENV__DOMAIN_NAME=https://$HOST
      - SYMFONY__ENV__SERVER_NAME="Johncloud wallabag"
      - SYMFONY__ENV__MAILER_DSN=$MAILER_DSN
      - SYMFONY__ENV__FROM_EMAIL=$FROM_EMAIL
    volumes:
      - wallabag_images:/var/www/wallabag/web/assets/images
      - wallabag_db:/var/www/wallabag/data
    depends_on:
      - redis
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`$HOST`)
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
        - traefik.http.routers.${COMPOSE_PROJECT_NAME}.service=${COMPOSE_PROJECT_NAME}
        - traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80

  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
    deploy:
      replicas: 1

volumes:
  wallabag_images:
  wallabag_db:

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    