version: '3.8'

services:
  db:
    image: supabase/postgres:15
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      replicas: 1

  auth:
    image: supabase/gotrue:latest
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    deploy:
      replicas: 1

  rest:
    image: supabase/postgrest:latest
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    deploy:
      replicas: 1

  realtime:
    image: supabase/realtime:latest
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USER: postgres
    deploy:
      replicas: 1

  studio:
    image: supabase/studio:latest
    # ports:
    #   - "8000:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: http://localhost:8000
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - auth
      - rest
      - realtime
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
        - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=3000"
        - "traefik.http.routers.$COMPOSE_PROJECT_NAME.middlewares=forward-auth-verify"
        - "homepage.group=$HOME_GROUP"
        - "homepage.name=$HOME_NAME"
        - "homepage.icon=$HOME_ICON"
        - "homepage.href=https://${HOST}"
        - "homepage.description=$HOME_DESCRIPTION"

volumes:
  db_data:

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    