# documentation: https://docs.pydio.com/cells-v4/admin-guide/quick-start/cells-installation/docker/#run-with-docker-compose
# slogan: The Secure Enterprise Content Management Platform
# tags: tag1,tag2,tag3
# logo: svgs/pydio.svg
# port: 8080

services:
  pydio:
    image: lscr.io/linuxserver/pydio-cells:latest
    volumes:
      - cellsdir:/config
    environment:
      - SERVICE_URL_PYDIO
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Paris}
      - EXTERNALURL=${SERVICE_URL_PYDIO}
  
  mysql:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${SERVICE_PASSWORD_PYDIODB}
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: ${SERVICE_PASSWORD_PYDIODB}
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - mysqldir:/var/lib/mysql

volumes:
  cellsdir: {}
  mysqldir: {}
  