services:
  duplicati:
    image: 'lscr.io/linuxserver/duplicati:latest'
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - 'TZ=${TZ:-Europe/London}'
      - 'SETTINGS_ENCRYPTION_KEY=${SERVICE_PASSWORD_ENCRYPT}'
      - 'DUPLICATI__WEBSERVICE_PASSWORD=${SERVICE_PASSWORD_WEB}'
    volumes:
      - '$JOHNCLOUD_ROOT/$COMPOSE_PROJECT_NAME/config:/config'
      - '$JOHNCLOUD_ROOT:/source'
    networks:
      tailscale:
        ipv4_address: $TAILSCALE_NET.201
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8200'
      interval: 2s
      timeout: 10s
      retries: 15
    labels:
      # - "traefik.enable=true"
      # - "traefik.http.routers.$COMPOSE_PROJECT_NAME.rule=Host(`$HOST`)"
      # - "traefik.http.routers.$COMPOSE_PROJECT_NAME.entrypoints=websecure"
      # - "traefik.http.routers.$COMPOSE_PROJECT_NAME.tls.certresolver=letsencrypt"
      # - "traefik.http.services.$COMPOSE_PROJECT_NAME.loadbalancer.server.port=8200"
      - "homepage.group=$HOME_GROUP"
      - "homepage.name=$HOME_NAME"
      - "homepage.icon=$HOME_ICON"
      - "homepage.href=https://$TAILSCALE_NET.201:8200/ngclient/"
      - "homepage.description=$HOME_DESCRIPTION"

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
  tailscale:
    external: true
    name: $TAILSCALE_NETWORK
    
    